# Generated by Django 5.2.8 on 2025-12-03 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_proficiency_level_category_skill_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('chain_3', '3-Person Chain (A→B→C→A)'), ('chain_4', '4-Person Chain (A→B→C→D→A)'), ('hour_pool', 'Hour Pool Exchange'), ('future_credit', 'Future Credit Exchange')], default='chain_3', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('participants_data', models.JSONField(default=dict, help_text='Structured data about proposed exchanges')),
                ('status', models.CharField(choices=[('generated', 'Generated - By system'), ('proposed', 'Proposed - Sent to users'), ('accepted', 'Accepted - All agreed'), ('rejected', 'Rejected - Not viable'), ('converted', 'Converted - To actual exchanges')], default='generated', max_length=20)),
                ('fairness_score', models.IntegerField(default=0, help_text='0-100 score of how fair the exchange is')),
                ('efficiency_score', models.IntegerField(default=0, help_text='0-100 score of chain efficiency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_to_users_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fairness_score', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_level',
        ),
        migrations.CreateModel(
            name='ExchangeChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional chain name', max_length=100)),
                ('status', models.CharField(choices=[('forming', 'Forming - Looking for participants'), ('proposed', 'Proposed - Chain identified'), ('pending', 'Pending - All parties reviewing'), ('accepted', 'Accepted - All parties agreed'), ('in_progress', 'In Progress - Chain active'), ('completed', 'Completed - All exchanges done'), ('cancelled', 'Cancelled - Chain abandoned')], default='forming', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Chain',
                'verbose_name_plural': 'Exchange Chains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Describe the service you can provide')),
                ('availability', models.CharField(blank=True, help_text='e.g., Weekends, Evenings', max_length=200)),
                ('hourly_rate_equivalent', models.DecimalField(decimal_places=2, default=25.0, help_text='Estimated market rate per hour (for fair exchange calculation)', max_digits=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by_users', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offered Skill',
                'verbose_name_plural': 'Offered Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('direct', 'Direct Exchange - Equal hourly value'), ('hourly', 'Hour Exchange - Hours for Hours'), ('value', 'Value Exchange - Based on hourly rates')], default='value', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('negotiating', 'Negotiating Terms'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('initiator_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('responder_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculated_ratio', models.DecimalField(decimal_places=3, default=1.0, help_text='Ratio of hours needed for fair exchange', max_digits=4)),
                ('initiator_hours_required', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('responder_hours_required', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of exchange in $ equivalent', max_digits=9)),
                ('is_balanced', models.BooleanField(default=False, help_text='Whether the exchange is financially balanced')),
                ('imbalance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monetary value difference if not perfectly balanced', max_digits=9)),
                ('terms', models.TextField(blank=True, help_text='Specific terms and conditions')),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('agreed_start_date', models.DateField(blank=True, null=True)),
                ('agreed_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('negotiated_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiator_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('responder_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('initiator_feedback', models.TextField(blank=True)),
                ('responder_feedback', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_exchanges', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responded_exchanges', to=settings.AUTH_USER_MODEL)),
                ('skill_from_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_offer', to='skills.offeredskill')),
                ('skill_from_responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_response', to='skills.offeredskill')),
            ],
            options={
                'verbose_name': 'Skill Exchange',
                'verbose_name_plural': 'Skill Exchanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeededSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Describe what service you need')),
                ('urgency', models.CharField(choices=[('low', 'Low - No rush'), ('medium', 'Medium - Within a month'), ('high', 'High - As soon as possible')], default='medium', max_length=20)),
                ('max_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Maximum hourly rate you're willing to exchange for this service", max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed_by_users', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Needed Skill',
                'verbose_name_plural': 'Needed Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_given', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('hours_received', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending - Not yet reviewed'), ('reviewing', 'Reviewing - Considering proposal'), ('accepted', 'Accepted - Agreed to participate'), ('rejected', 'Rejected - Declined to participate')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_participations', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_links', to='skills.exchangechain')),
                ('gives_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_in_chains', to='skills.offeredskill')),
                ('receives_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_in_chains', to='skills.offeredskill')),
            ],
            options={
                'ordering': ['chain', 'position'],
                'unique_together': {('chain', 'position'), ('chain', 'user')},
            },
        ),
    ]
