# Generated by Django 5.2.8 on 2025-12-03 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_brokerproposal_remove_skill_proficiency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='hours_given',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='hours_received',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='skillexchange',
            name='calculated_ratio',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Ratio of hours needed for fair exchange', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skillexchange',
            name='initiator_hours_required',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='skillexchange',
            name='responder_hours_required',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
