# Generated by Django 5.2.8 on 2025-12-03 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_chainlink_hours_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillexchange',
            name='calculated_ratio',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Ratio of hours needed for fair exchange', max_digits=6),
        ),
        migrations.AlterField(
            model_name='skillexchange',
            name='initiator_hours_required',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='skillexchange',
            name='responder_hours_required',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
