# Generated by Django 5.2.8 on 2025-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_skillexchange_calculated_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillexchange',
            name='calculated_ratio',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Ratio of hours needed for fair exchange', max_digits=10),
        ),
    ]
