# Generated by Django 5.2.8 on 2025-12-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_skillexchange_calculated_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='categories',
        ),
    ]
